### ISSUE TITLE
 Paste text in field does not work

### ISSUE THREAD

**Issue by joohncruz** [vanilla-masker/vanilla-masker#108]
I'm using a directive made with the vues to assign the mask. But I made a change to be dynamic based on value.

But when I click on the field and paste the contents directly the masks do not work.

Has anyone ever experienced this?

```
export const Phone = {
  bind(el) {
    const pattern = '(99) 9999-99999';
    vanillaMasker(el).maskPattern(pattern);
  },
  componentUpdated(el, binding) {
    const patterns = ['(99) 9999-99999', '(99) 99999-9999']

    let value = $(el).val()
    let v = value.replace(/\D/g, '');
    let m = value.length > 14 ? 1: 0;

    vanillaMasker(el).unMask();
    vanillaMasker(el).maskPattern(patterns[m]);
    el.value = vanillaMasker.toPattern(v, patterns[m]);

  }
```

Paste: 
![image](https://cloud.githubusercontent.com/assets/7672428/23783954/d957cf1a-053d-11e7-9a8f-aa08db289fd4.png)

Writing:
![image](https://cloud.githubusercontent.com/assets/7672428/23783971/f0a6961a-053d-11e7-9fc2-bcf33651a353.png)

Thnx!

**Comment by netpoetica** [comment]
One thing - I don't think you should be unMasking and maskPattern again every time the component updates. You could do that one time in the mounting stage and then just use `toPattern()` onChange.

From what I can see here, it looks like for some reason there is a difference between value.length when you paste and when you type it manually, because it's just ending up using a different pattern, but still one of the patterns you specified. I would look into what the value of `value.length` is each time you paste vs. each time you enter a number with the keyboard.
